# Generated by Django 3.0.4 on 2020-03-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nome',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
