# Generated by Django 3.0.4 on 2020-03-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_auto_20200319_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nome',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
